//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXEMAIL_SENDEMAILGUI_WXCRAFTER_BASE_CLASSES_H
#define WXEMAIL_SENDEMAILGUI_WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/notebook.h>
#include <wx/imaglist.h>
#include <wx/statbox.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/filepicker.h>
#include <wx/stc/stc.h>
#include <wx/button.h>
#include <wx/menu.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class MainFrameBaseClass : public wxFrame
{
protected:
    wxPanel* m_mainPanel;
    wxNotebook* m_notebook;
    wxPanel* m_panel60;
    wxStaticText* m_staticText34;
    wxTextCtrl* m_textCtrlGmail;
    wxStaticText* m_staticText36;
    wxTextCtrl* m_textCtrlPassword;
    wxStaticText* m_staticText38;
    wxTextCtrl* m_textCtrlSmtp;
    wxStaticText* m_staticText49;
    wxTextCtrl* m_textCtrlFrom;
    wxStaticText* m_staticText43;
    wxTextCtrl* m_textCtrlTo;
    wxStaticText* m_staticText45;
    wxTextCtrl* m_textCtrlSubject;
    wxStaticText* m_staticText53;
    wxFilePickerCtrl* m_filePickerAttachment;
    wxStaticText* m_staticText72;
    wxFilePickerCtrl* m_filePickerAttachment2;
    wxStaticText* m_staticText47;
    wxTextCtrl* m_textCtrlBody;
    wxPanel* m_panel62;
    wxStyledTextCtrl* m_stcRaw;
    wxButton* m_button19;
    wxButton* m_button68;
    wxMenuBar* m_menuBar;
    wxMenu* m_name6;
    wxMenuItem* m_menuItem7;
    wxMenu* m_name8;
    wxMenuItem* m_menuItem9;

protected:
    virtual void OnSend(wxCommandEvent& event) { event.Skip(); }
    virtual void OnInspect(wxCommandEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText34() { return m_staticText34; }
    wxTextCtrl* GetTextCtrlGmail() { return m_textCtrlGmail; }
    wxStaticText* GetStaticText36() { return m_staticText36; }
    wxTextCtrl* GetTextCtrlPassword() { return m_textCtrlPassword; }
    wxStaticText* GetStaticText38() { return m_staticText38; }
    wxTextCtrl* GetTextCtrlSmtp() { return m_textCtrlSmtp; }
    wxStaticText* GetStaticText49() { return m_staticText49; }
    wxTextCtrl* GetTextCtrlFrom() { return m_textCtrlFrom; }
    wxStaticText* GetStaticText43() { return m_staticText43; }
    wxTextCtrl* GetTextCtrlTo() { return m_textCtrlTo; }
    wxStaticText* GetStaticText45() { return m_staticText45; }
    wxTextCtrl* GetTextCtrlSubject() { return m_textCtrlSubject; }
    wxStaticText* GetStaticText53() { return m_staticText53; }
    wxFilePickerCtrl* GetFilePickerAttachment() { return m_filePickerAttachment; }
    wxStaticText* GetStaticText72() { return m_staticText72; }
    wxFilePickerCtrl* GetFilePickerAttachment2() { return m_filePickerAttachment2; }
    wxStaticText* GetStaticText47() { return m_staticText47; }
    wxTextCtrl* GetTextCtrlBody() { return m_textCtrlBody; }
    wxPanel* GetPanel60() { return m_panel60; }
    wxStyledTextCtrl* GetStcRaw() { return m_stcRaw; }
    wxPanel* GetPanel62() { return m_panel62; }
    wxNotebook* GetNotebook() { return m_notebook; }
    wxButton* GetButton19() { return m_button19; }
    wxButton* GetButton68() { return m_button68; }
    wxPanel* GetMainPanel() { return m_mainPanel; }
    wxMenuBar* GetMenuBar() { return m_menuBar; }
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("My Frame"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxCAPTION|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

#endif
